### ISSUE TITLE
Dual licensed?

### ISSUE THREAD

**Issue by palmskog** [barry-jay-personal/tree-calculus#2]
Regarding the license for this project, the file headers say LGPL-2.1-or-later, while the `LICENSE` file says it's the MIT license. The only way I can reconcile this apparent contradiction is that the project can be licensed under *either* LGPL or MIT, at the user's discretion (dual licensing). Is this the case? Or which license is the canonical one?

**Comment by barry-jay-personal** [comment]
Hi Karl,

when preparing the files for packaging, I shifted the license to MIT, as
per the Coq community's preference. Something must have gone wrong along
the way! I will fix this up in the next few days. Thanks for pointing this
out.

Yours,
Barry

**Comment by barry-jay-personal** [comment]
Hi Karl,

I've changed all licenses to MIT now, and created a new release. Hopefully
that is all fixed now. Thanks again; do let me know if you find anything
else.

Yours,
Barry

**Comment by palmskog** [comment]
Looks good to me with only MIT license now, so closing this issue.
