### ISSUE TITLE
A Beautiful and Elegant Calculus

### ISSUE THREAD

**Issue by zpyatt** [barry-jay-personal/tree-calculus#4]
Congratulations, and thank you for this elegant calculus. W.R.T. "who cares about programs in your SF-calculus?" - I am, and I'd think anyone who appreciates beauty and cares about computation would be as well. I've followed your work since I discovered "Programs as Data Structures", frequently checking for new calculi (you kind of lost me after λSF), tree calculus didn't disappoint, it's so cool/fascinating. I'm working on a C++ implementation (I'm close) so I can play with it, to discover its capabilities/implications. 

I was wondering:
1.) Are you interested in comments on the book? If so is this an appropriate forum?
2.) Is this an appropriate forum for discussing / asking questions about tree calculus?

Anyway, keep up the good work! It's greatly appreciated. I think tree calculus may be more beautiful than lambda calculus, which in my mind sets the bar for simplicity and elegance.

**Comment by barry-jay-personal** [comment]
Hi zpyatt,

Thanks for the compliments!  I’m not sure what magazine this is whose “Issue #4” you refer to. 
Do let me know how your implementation works out. Certainly, all questions and comments are welcome.

Yours,
Barry

**Comment by zpyatt** [comment]
Barry, 

Issue #4 is the "issue" number Github assigned, since I posted this as an "issue" on Github. Is there a better place to comment and discuss? I can close this if you like.

Thanks,
/ZRP

**Comment by barry-jay-personal** [comment]
Oh, understood. Just email will be fine for now.
B
